version: '3'
services:
  db:
    image: tutoweb
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    hostname: redis

  web:
    image: tutoweb
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - 'redis'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/myapp'
    env_file:
      - 'config.env'
